name: Update README from Model Aliases

on:
  push:
    branches:
      - main # Or 'master', or your default branch name
    paths:
      - 'model_aliases.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Show current directory and its contents
        run: |
          pwd
          echo "--- Listing files in current directory (GITHUB_WORKSPACE): ---"
          ls -la
          echo "-----------------------------------------------------------"

      - name: Run script to generate README.md
        run: python create_readme.py

      - name: Commit and push if README.md changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-update README.md from model_aliases.yml"
          file_pattern: README.md
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
